/**
 * Tests notify-mailer.ts in isolation. Sends a real email with a dummy .docx attachment.
 * Run: npx ts-node src/scripts/test-mailer.ts
 */
import * as dotenv from "dotenv";
dotenv.config();

import * as fs from "node:fs";
import * as path from "node:path";
import { sendProposalEmail } from "../trigger/lib/notify-mailer";
import type { ProposalDocument } from "../trigger/types";

const sampleProposal: ProposalDocument = {
  leadData: {
    source: "typeform",
    sourceId: "test-001",
    receivedAt: new Date().toISOString(),
    prospectName: "John Smith",
    companyName: "Acme Corp",
    contactEmail: "john@acmecorp.com",
    requirementDescription:
      "Automate all tech debt across all our projects — legacy cleanup, dependency upgrades, CI/CD improvements.",
    timeline: "3 months",
    teamSize: "12 engineers",
    managerEmail: process.env.MANAGER_EMAIL ?? "",
  },
  generatedAt: new Date().toISOString(),
  sections: {
    executiveSummary: "This is a test proposal generated by the automated proposal system. Executive summary placeholder content for email test.",
    requirementsUnderstanding: "Test content.",
    proposedSolution: "Test content.",
    projectTimeline: "Test content.",
    teamAndResources: "Test content.",
    investmentPricing: "Test content.",
    whyUs: "Test content.",
    deliverables: "Test content.",
    nextSteps: "Test content.",
    termsAndConditions: "Test content.",
  },
};

async function main() {
  if (!process.env.MANAGER_EMAIL) {
    console.error("MANAGER_EMAIL env var is not set — cannot send test email.");
    process.exit(1);
  }

  console.log(`Testing notify-mailer — sending to: ${process.env.MANAGER_EMAIL}\n`);

  // Use local docx if available, otherwise send a small placeholder
  const localDocx = path.join(process.cwd(), "test-output-proposal.docx");
  const docxBuffer = fs.existsSync(localDocx)
    ? fs.readFileSync(localDocx)
    : Buffer.from("Placeholder DOCX content for email test");

  await sendProposalEmail({
    proposal: sampleProposal,
    docxBuffer,
    driveLink: "https://drive.google.com/test-link",
    fileName: "TEST_Proposal_Acme_Corp.docx",
  });

  console.log("Email sent successfully.");
  console.log(`Check inbox: ${process.env.MANAGER_EMAIL}`);
  console.log("Verify: subject contains company name, .docx is attached, Drive link button is visible.");
}

main().catch(console.error);
